# Screen Configuration
screen:
  width: 800
  height: 600
  caption: "Draugr's Descent"
  frame_rate: 60

# Colors (RGB)
colors:
  black: [0, 0, 0]
  red: [255, 0, 0]
  green: [0, 255, 0]
  white: [255, 255, 255]
  blue: [0, 0, 255]
  yellow: [255, 255, 0]
  purple: [255, 0, 255]
  dark_blue: [20, 30, 50]  # Added for menu background

# Game Mechanics
mechanics:
  enemy_spawn:
    interval: 1000  # milliseconds - base spawn interval
    margin: 30  # Pixels offset from map edge for spawning enemies
    min_interval: 250  # Minimum spawn interval in milliseconds (fastest possible spawn rate)
    scaling_factor: 0.85  # Factor for exponential spawn rate increase (lower = faster increase)
    scaling_interval: 30000  # Time between difficulty increases in milliseconds (30 seconds)
  player:
    shooting_range: 300  # Maximum distance player projectiles can travel

# Player Settings
player:
  dimensions:
    width: 60
    height: 60
  start_position:
    x: 400
    y: 300
  attributes:
    max_health: 100
    movement_speed: 5
    shot_cooldown: 500  # milliseconds
    invincibility_duration: 300  # milliseconds
  appearance:
    color: "green"  # Options: green, purple, red, yellow - matches scribble_dungeons characters

# Enemy Settings
enemy:
  dimensions:
    width: 45
    height: 45
  attributes:
    max_health: 20
    damage: 10
    speed: 2
  appearance:
    basic:
      color: "purple"  # Basic enemies will use purple character sprite
    ranged:
      color: "red"  # Ranged enemies will use red character sprite
    charger:
      color: "yellow"  # Charger enemies will use yellow character sprite
  # New enemy type settings
  ranged:
    preferred_distance: 200
    attack_cooldown: 2000  # milliseconds
    projectile_speed: 5
    projectile_damage: 5
    speed: 1.5
    max_health: 15
  charger:
    charge_distance: 150
    charge_cooldown: 3000  # milliseconds
    charge_duration: 1000  # milliseconds
    charge_speed_multiplier: 3
    speed: 1.8
    max_health: 50
  # Spawn weights for different enemy types (out of 100)
  spawn_weights:
    basic: 50
    ranged: 30
    charger: 20

# Projectile Settings
projectile:
  dimensions:
    width: 10
    height: 10
  attributes:
    damage: 10

# UI Elements
ui:
  # General UI settings
  default_theme: "blue"  # Default UI theme color
  available_themes: ["blue", "green", "grey", "red", "yellow"]
  
  # Health bar settings  
  health_bar:
    width: 200
    height: 20
    border_color: "black"
    fill_color: "green"
    background_color: "red"
    
  # Main menu settings
  main_menu:
    background_color: "dark_blue"  # Reference to colors section
    panel:
      width_ratio: 0.4  # Percentage of screen width
      height_ratio: 0.4  # Percentage of screen height
    title:
      font_size: 36
      color: "white"
      y_offset: -40  # Pixels above panel top
    buttons:
      width_ratio: 0.7  # Percentage of panel width
      height: 45
      spacing: 60
      start_y_offset: 60
      text_color: "white"
      font_size: 24
  
  # Pause menu settings
  pause_menu:
    overlay_color: [0, 0, 0, 128]  # RGBA with alpha for transparency
    panel:
      width_ratio: 0.4
      height_ratio: 0.6
    title:
      font_size: 32
      color: "white"
    buttons:
      width_ratio: 0.7
      height: 45
      spacing: 50
      text_color: "white"
      font_size: 20
  
  # Options menu settings
  options_menu:
    overlay_color: [0, 0, 0, 200]  # RGBA with alpha for transparency
    panel:
      width_ratio: 0.7
      height_ratio: 0.7
    title:
      font_size: 32
      color: "white"
    buttons:
      width_ratio: 0.7
      height: 45
      spacing: 60
      text_color: "white"
      font_size: 20
    sections:
      audio:
        title: "Audio"
        font_size: 24
      display:
        title: "Display"
        font_size: 24
      controls:
        title: "Controls"
        font_size: 24
    sliders:
      width: 200
      height: 20
      knob_size: 30
      text_color: "white"
      track_color: "blue"  # Color theme for slider tracks
      knob_color: "blue"   # Color theme for slider knobs
  
  # Game HUD settings
  game_hud:
    score:
      position_x: 20
      position_y: 20
      font_size: 24
      color: "white"
    health:
      position_x: 20
      position_y: 50
      font_size: 20
      color: "white"
    powerups:
      position_x: 650
      position_y: 20
      icon_size: 30
      spacing: 10
    wave_announcement:
      font_size: 40
      color: "yellow"
      duration: 3000  # milliseconds

  # Game Over Menu UI Settings
  game_over:
    background_color: black
    panel:
      width_ratio: 0.5
      height_ratio: 0.7
    title:
      font_size: 48
      color: red
    stats:
      font_size: 22
      text_color: white
      score_color: yellow
    buttons:
      width_ratio: 0.6
      height: 45
      spacing: 60
      font_size: 24
      text_color: white

# Effect settings
effects:
  screen_shake:
    duration: 300   # Duration in milliseconds
    intensity: 15   # Maximum pixel offset (increased for more noticeable effect)

# Particle Effects
particles:
  enabled: true  # Global toggle for particle effects
  types:
    hit:  # Projectile hit particles
      count: 12  # Number of particles per effect
      min_speed: 2.0
      max_speed: 4.0
      min_lifetime: 400  # ms
      max_lifetime: 800  # ms
      colors: ["yellow", "orange", "red"]
      size_range: [4, 8]  # min and max pixel size
      gravity: 0.1  # Downward acceleration
      fade_out: true  # Whether particles should fade out over lifetime
    
    death:  # Enemy death particles
      count: 20
      min_speed: 3.0
      max_speed: 6.0
      min_lifetime: 600  # ms
      max_lifetime: 1200  # ms
      colors: ["red", "dark_red", "orange"]
      size_range: [5, 10]  # Larger particles
      gravity: 0.05
      fade_out: true
      
    powerup:  # Powerup collection particles
      count: 12
      min_speed: 1.0
      max_speed: 3.0
      min_lifetime: 600  # ms
      max_lifetime: 900  # ms
      colors: ["green", "yellow", "blue"]
      size_range: [2, 4]
      gravity: -0.05  # Negative gravity makes particles float up
      fade_out: true

# Powerup Settings
powerups:
  dimensions:
    width: 25
    height: 25
  effects:
    health_restore: 25
    shield_duration: 5000  # milliseconds
    speed_boost: 2
    speed_duration: 5000  # milliseconds
    weapon_boost: 0.5
    weapon_duration: 5000  # milliseconds
  colors:
    health: [0, 255, 0]
    shield: [0, 0, 255]
    speed: [255, 255, 0]
    weapon: [255, 165, 0]

# Scoring
scoring:
  basic_enemy: 10
  ranged_enemy: 20
  charger_enemy: 30
  powerup_collected: 5

# Asset Paths
assets:
  images:
    path: "assets/images"
    player: "player.png"
    enemy: "enemy.png"
    projectile: "projectile.png"
    powerups:
      health: "powerup_health.png"
      shield: "powerup_shield.png"
      speed: "powerup_speed.png"
  sounds:
    path: "assets/sounds"
    background_music: "background.mp3"
    shoot: "shoot.wav"
    hit: "hit.wav"
    powerup: "powerup.wav"
  fonts:
    path: "assets/fonts"
    main: "main_font.ttf"
    sizes:
      title: 36
      button: 24
      small: 18
      large: 32
  interface:
    path: "assets/interface"
    spritesheet_path: "Spritesheet"